/**
 * @fileoverview Standard Event Types
 * @author Frederik Krautwald
 * @copyright 2015 Cyclic Materials. All rights reserved.
 */

// https://developer.mozilla.org/en-US/docs/Web/Events
const standardEventTypes = {
  abort: true,
  afterprint: true,
  animationend: true,
  animationiteration: true,
  animationstart: true,
  audioprocess: true,
  audioend: true,
  audiostart: true,
  beforeprint: true,
  beforeunload: true,
  beginEvent: true,
  blocked: true,
  blur: true,
  cached: true,
  canplay: true,
  canplaythrough: true,
  change: true,
  chargingchange: true,
  chargingtimechange: true,
  checking: true,
  click: true,
  close: true,
  complete: true,
  compositionend: true,
  compositionstart: true,
  compositionupdate: true,
  contextmenu: true,
  copy: true,
  cut: true,
  dblclick: true,
  devicelight: true,
  devicemotion: true,
  deviceorientation: true,
  deviceproximity: true,
  dischargingtimechange: true,
  DOMActivate: true,
  DOMAttributeNameChanged: true,
  DOMAttrModified: true,
  DOMCharacterDataModified: true,
  DOMContentLoaded: true,
  DOMElementNameChanged: true,
  DOMFocusIn: true,
  DOMFocusOut: true,
  DOMNodeInserted: true,
  DOMNodeInsertedIntoDocument: true,
  DOMNodeRemoved: true,
  DOMNodeRemovedFromDocument: true,
  DOMSubtreeModified: true,
  downloading: true,
  drag: true,
  dragend: true,
  dragenter: true,
  dragleave: true,
  dragover: true,
  dragstart: true,
  drop: true,
  durationchange: true,
  emptied: true,
  end: true,
  ended: true,
  endEvent: true,
  focus: true,
  focusin: true,
  focusout: true,
  fullscreenchange: true,
  fullscreenerror: true,
  gamepadconnected: true,
  gamepaddisconnected: true,
  gotpointercapture: true,
  hashchange: true,
  lostpointercapture: true,
  input: true,
  invalid: true,
  keydown: true,
  keypress: true,
  keyup: true,
  languagechange: true,
  levelchange: true,
  load: true,
  loadeddata: true,
  loadedmetadata: true,
  loadend: true,
  loadstart: true,
  message: true,
  mousedown: true,
  mouseenter: true,
  mouseleave: true,
  mousemove: true,
  mouseout: true,
  mouseover: true,
  mouseup: true,
  nomatch: true,
  notificationclick: true,
  noupdate: true,
  obsolete: true,
  offline: true,
  online: true,
  open: true,
  orientationchange: true,
  pagehide: true,
  pageshow: true,
  paste: true,
  pause: true,
  pointercancel: true,
  pointerdown: true,
  pointerenter: true,
  pointerleave: true,
  pointerlockchange: true,
  pointerlockerror: true,
  pointermove: true,
  pointerout: true,
  pointerover: true,
  pointerup: true,
  play: true,
  playing: true,
  popstate: true,
  progress: true,
  push: true,
  pushsubscriptionchange: true,
  ratechange: true,
  readystatechange: true,
  repeatEvent: true,
  reset: true,
  resize: true,
  result: true,
  scroll: true,
  seeked: true,
  seeking: true,
  select: true,
  selectstart: true,
  selectionchange: true,
  show: true,
  soundend: true,
  soundstart: true,
  speechend: true,
  speechstart: true,
  stalled: true,
  start: true,
  storage: true,
  submit: true,
  success: true,
  suspend: true,
  SVGAbort: true,
  SVGError: true,
  SVGLoad: true,
  SVGResize: true,
  SVGScroll: true,
  SVGUnload: true,
  SVGZoom: true,
  timeout: true,
  timeupdate: true,
  touchcancel: true,
  touchend: true,
  touchenter: true,
  touchleave: true,
  touchmove: true,
  touchstart: true,
  transitionend: true,
  unload: true,
  updateready: true,
  upgradeneeded: true,
  userproximity: true,
  versionchange: true,
  visibilitychange: true,
  volumechange: true,
  waiting: true,
  wheel: true,
}

//const hammerEventTable = {
//  pan: true,
//  panstart: true,
//  panmove: true,
//  panend: true,
//  pancancel: true,
//  panleft: true,
//  panright: true,
//  panup: true,
//  pandown: true,
//  pinch: true,
//  pinchstart: true,
//  pinchmove: true,
//  pinchend: true,
//  pinchcancel: true,
//  pinchin: true,
//  pinchout: true,
//  press: true,
//  pressup: true,
//  rotate: true,
//  rotatestart: true,
//  rotatemove: true,
//  rotateend: true,
//  rotatecancel: true,
//  swipe: true,
//  swipeleft: true,
//  swiperight: true,
//  swipeup: true,
//  swipedown: true,
//  tap: true,
//}

export default standardEventTypes
